### ISSUE TITLE
Half of calculated features were unused in SVM

### ISSUE THREAD

**Issue by kwatcharasupat** [FBA-Janitor/MIG-MusicPerformanceAnalysis-Code#6]
Bug originally found by Yiwei. 

cc: @alexanderlerch 

https://github.com/FBA-Janitor/MIG-MusicPerformanceAnalysis-Code/blob/ec8843cac4d7740af8ace3edfe2224e7e8bcb34e/src/auto_segmentation/src/ProcessInput.py#L120-L124

Half of the MIR/MFCC features were ignored in the original code. `row +=2` caused only every other feature in `featureArr` to be used.

Proposed fix:
```python
for row in range(featureRows):
    featArrCongregate[2*row, block] = float(np.mean(featureArr[row, startCol:endCol]))
    featArrCongregate[2*row + 1, block] = float(np.std(featureArr[row, startCol:endCol]))
```

**Comment by kwatcharasupat** [comment]
Bug will be left unfixed until all the codes are back up and running.

**Comment by alexanderlerch** [comment]
Oh my. Good catch.

**Comment by alexanderlerch** [comment]
Maybe do a pull request (we merge later)?

**Comment by suncerock** [comment]
What about just leaving the old code there for now? Cuz I'm writing the new code (with the bug unfixed) and the bug is marked with a FIXME in the new code. Fixing the bug means we should retrain the model, which will be at least, maybe two or three weeks later. 

The new code I'm processing is pushed directly into the main branch.

**Comment by alexanderlerch** [comment]
Please hold back a little bit with rewriting anything, and if you do, make sure you have tests in place to verify equivalency. I want to strongly discourage you from rewriting and fixing at the same time.

**Comment by suncerock** [comment]
Get it, then adding a pull request might be a good idea to get the old code do the right thing.

Then I will do the fix first, then try to restructure it.

**Comment by suncerock** [comment]
The bug is fixed in the new auto segmentation code.
