### ISSUE TITLE
Special cases will cause smoothing in post processsing to fail (no error message)

### ISSUE THREAD

**Issue by suncerock** [FBA-Janitor/MIG-MusicPerformanceAnalysis-Code#7]
A bug will cause the smoothing in post processing to fail in special cases

cc: @karnwatcharasupat @alexanderlerch 

https://github.com/FBA-Janitor/MIG-MusicPerformanceAnalysis-Code/blob/ec8843cac4d7740af8ace3edfe2224e7e8bcb34e/src/auto_segmentation/src/Classification_Annotation.py#L136-L154

Here, the codes are trying to find the (0, 1, 0) patterns and (1, 0, 1) patterns in the raw prediction results `predictions` and replace them with (0, 0, 0) and (1, 1, 1) because they suppose there should be no such short performance or non-performance segments.

The codes go into the `if` branch in line 141 and 151 if there exists a (0, 1) or (1, 0) pattern in last three frames of `prediction`. It works well when this happens at `predictions[-2:]`, the last `m3` and `m1` are discarded to avoid index error next line. However, if this happens at `predictions[-3:-1]`, `np.sum(m3 >= len(predDiff) - 1` gives `0` and `m3` (or `m1`) will be set to an empty array. All the patterns detected before the last three frames are lost, causing the smoothing to lose its effectiveness.

Fixing the bug should not make a big difference and will not require to retrain the model.

**Comment by alexanderlerch** [comment]
Ok, this is hard for me to see at a glance without diving into it. Could someone else verify?

**Comment by suncerock** [comment]
The bug is fixed in the new auto segmentation code.
